[package]
name = "ba_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iou = "0.3.3"
rand = "0.8.5"
rio = "0.9.4"
